### ISSUE TITLE
How to set "--gradloss_weight"

### ISSUE THREAD

**Issue by DaxingZ** [lusinlu/gradient_variance_loss#3]
The "--gradloss_weight" was set to 0.01 in the MSE+GV Loss mode. How to set it when using other loss functions, such as L1?

**Comment by lusinlu** [comment]
When setting the weight of the gradloss you should consider that it is an auxiliary loss and its values should be lower than the values of the main loss (L1, L2...). For the rest, it is depend on the task how smaller it should be

**Comment by DaxingZ** [comment]
Thanks for your detailed reply ^-^
